export const PERMISSIONS = {
  decisionRead: "decision.read",
  decisionWrite: "decision.write",
  decisionActivate: "decision.activate",
  decisionArchive: "decision.archive",
  stackRead: "stack.read",
  stackWrite: "stack.write",
  stackActivate: "stack.activate",
  stackArchive: "stack.archive",
  offerRead: "catalog.offer.read",
  offerWrite: "catalog.offer.write",
  offerActivate: "catalog.offer.activate",
  offerArchive: "catalog.offer.archive",
  contentRead: "catalog.content.read",
  contentWrite: "catalog.content.write",
  contentActivate: "catalog.content.activate",
  contentArchive: "catalog.content.archive",
  engageAppRead: "engage.app.read",
  engageAppWrite: "engage.app.write",
  engageAppActivate: "engage.app.activate",
  engageAppArchive: "engage.app.archive",
  engagePlacementRead: "engage.placement.read",
  engagePlacementWrite: "engage.placement.write",
  engagePlacementActivate: "engage.placement.activate",
  engagePlacementArchive: "engage.placement.archive",
  engageTemplateRead: "engage.template.read",
  engageTemplateWrite: "engage.template.write",
  engageTemplateActivate: "engage.template.activate",
  engageTemplateArchive: "engage.template.archive",
  engageCampaignRead: "engage.campaign.read",
  engageCampaignWrite: "engage.campaign.write",
  engageCampaignActivate: "engage.campaign.activate",
  engageCampaignArchive: "engage.campaign.archive",
  logsRead: "logs.read",
  logsExport: "logs.export",
  cacheRead: "cache.read",
  cacheInvalidate: "cache.invalidate",
  dlqRead: "dlq.read",
  dlqRetry: "dlq.retry",
  dlqQuarantine: "dlq.quarantine",
  dlqResolve: "dlq.resolve",
  precomputeRun: "precompute.run",
  precomputeRead: "precompute.read",
  resultsRead: "results.read",
  settingsWbsRead: "settings.wbs.read",
  settingsWbsWrite: "settings.wbs.write",
  settingsWbsMappingRead: "settings.wbsMapping.read",
  settingsWbsMappingWrite: "settings.wbsMapping.write",
  settingsPipesRead: "settings.pipes.read",
  settingsPipesWrite: "settings.pipes.write",
  settingsWebhooksRead: "settings.webhooks.read",
  settingsWebhooksWrite: "settings.webhooks.write",
  settingsAppRead: "settings.app.read",
  settingsAppWrite: "settings.app.write",
  promotionCreate: "promotion.create",
  promotionApprove: "promotion.approve",
  promotionApply: "promotion.apply",
  auditRead: "audit.read",
  userManage: "user.manage",
  roleManage: "role.manage",
  simulatorRun: "simulator.run"
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

const allPermissionValues = Object.values(PERMISSIONS);

export const allPermissions = (): string[] => [...allPermissionValues];

const withPrefix = (prefix: "engage.app" | "engage.placement" | "engage.template" | "engage.campaign") => [
  `${prefix}.read`,
  `${prefix}.write`,
  `${prefix}.activate`,
  `${prefix}.archive`
];
const readOnlyWithPrefix = (prefix: "engage.app" | "engage.placement" | "engage.template" | "engage.campaign") => [
  `${prefix}.read`
];

export const defaultRolePermissions: Record<string, string[]> = {
  viewer: [
    PERMISSIONS.decisionRead,
    PERMISSIONS.stackRead,
    PERMISSIONS.offerRead,
    PERMISSIONS.contentRead,
    ...readOnlyWithPrefix("engage.app"),
    ...readOnlyWithPrefix("engage.placement"),
    ...readOnlyWithPrefix("engage.template"),
    ...readOnlyWithPrefix("engage.campaign"),
    PERMISSIONS.logsRead,
    PERMISSIONS.cacheRead,
    PERMISSIONS.precomputeRead,
    PERMISSIONS.resultsRead,
    PERMISSIONS.settingsWbsRead,
    PERMISSIONS.settingsWbsMappingRead,
    PERMISSIONS.settingsPipesRead,
    PERMISSIONS.settingsWebhooksRead,
    PERMISSIONS.settingsAppRead,
    PERMISSIONS.simulatorRun,
    PERMISSIONS.auditRead
  ],
  builder: [
    PERMISSIONS.decisionRead,
    PERMISSIONS.decisionWrite,
    PERMISSIONS.stackRead,
    PERMISSIONS.stackWrite,
    PERMISSIONS.offerRead,
    PERMISSIONS.offerWrite,
    PERMISSIONS.contentRead,
    PERMISSIONS.contentWrite,
    PERMISSIONS.engageCampaignRead,
    PERMISSIONS.engageCampaignWrite,
    PERMISSIONS.simulatorRun
  ],
  publisher: [
    PERMISSIONS.decisionRead,
    PERMISSIONS.decisionWrite,
    PERMISSIONS.decisionActivate,
    PERMISSIONS.decisionArchive,
    PERMISSIONS.stackRead,
    PERMISSIONS.stackWrite,
    PERMISSIONS.stackActivate,
    PERMISSIONS.stackArchive,
    PERMISSIONS.offerRead,
    PERMISSIONS.offerWrite,
    PERMISSIONS.offerActivate,
    PERMISSIONS.offerArchive,
    PERMISSIONS.contentRead,
    PERMISSIONS.contentWrite,
    PERMISSIONS.contentActivate,
    PERMISSIONS.contentArchive,
    ...withPrefix("engage.app"),
    ...withPrefix("engage.placement"),
    ...withPrefix("engage.template"),
    ...withPrefix("engage.campaign"),
    PERMISSIONS.promotionCreate,
    PERMISSIONS.simulatorRun
  ],
  operator: [
    PERMISSIONS.logsRead,
    PERMISSIONS.logsExport,
    PERMISSIONS.cacheRead,
    PERMISSIONS.cacheInvalidate,
    PERMISSIONS.dlqRead,
    PERMISSIONS.dlqRetry,
    PERMISSIONS.dlqQuarantine,
    PERMISSIONS.dlqResolve,
    PERMISSIONS.precomputeRead,
    PERMISSIONS.precomputeRun,
    PERMISSIONS.resultsRead,
    PERMISSIONS.auditRead
  ],
  admin: allPermissionValues
};
